MVCDatabase/Models/jobModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace MVCDatabase.Models
{
    public class jobModel
    {
        public int jobID { get; set; }


        [DisplayName("Task Name")]
        public string taskName { get; set; }


        [DisplayName("Description")]
        public string description { get; set; }


        [DisplayName("Date Started")]
        public string dateStarted { get; set; }

        [DisplayName("Date Finished")]
        public string dateFinished { get; set; }
 
        [DisplayName("Status")]
        public string status { get; set; }
 
    }
}

MVCDatabase/Controllers/jobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCDatabase.Models;
using MySql.Data.MySqlClient;
using System.Data;
using System.Configuration;


namespace MVCDatabase.Controllers
{
    public class jobController : Controller
    {
        

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(jobModel job)
        {
            {
                string connectionString = @"server=localhost;user id=root;database=mvcdb";
                MySqlConnection connection = null;


                connection = new MySqlConnection(connectionString);
                connection.Open();
                MySqlCommand cmd = new MySqlCommand();
                cmd.Connection = connection;
                cmd.CommandText = "INSERT INTO `job info`(`Task Name`, `Description`, `Date Started`, `Date Finished`, `Status`) VALUES (@taskName, @description, @dateStarted, @dateFinished, @status)";

                cmd.Parameters.AddWithValue("@taskName", job.taskName);
                cmd.Parameters.AddWithValue("@description", job.description);
                cmd.Parameters.AddWithValue("@dateStarted", job.dateStarted);
                cmd.Parameters.AddWithValue("@dateFinished", job.dateFinished);
                cmd.Parameters.AddWithValue("@status", job.status);

                cmd.ExecuteNonQuery();

                return View(job);
            }
        }

        public ActionResult List()
        {
            string connectionString = @"server=localhost;user id=root;database=mvcdb";
            string select = "SELECT * FROM `job info`";

            DataTable dtblProduct = new DataTable();
            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                MySqlDataAdapter da = new MySqlDataAdapter(select, connection);
                da.Fill(dtblProduct);
            }
            return View(dtblProduct);
        }

        //
        [HttpGet]
        public ActionResult Edit(int id)
        {
            string connectionString = @"server=localhost;user id=root;database=mvcdb";
            jobModel job = new jobModel();
            DataTable dtblProduct = new DataTable();


            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                string select = "SELECT * FROM  `job info` WHERE JobID = @jobID";
                MySqlDataAdapter da = new MySqlDataAdapter(select, connection);
                da.SelectCommand.Parameters.AddWithValue("@jobID", id);
                da.Fill(dtblProduct);

            }

            if (dtblProduct.Rows.Count == 1)
            {
                job.jobID = Convert.ToInt32(dtblProduct.Rows[0][0]);
                job.taskName = dtblProduct.Rows[0][1].ToString();
                job.description = dtblProduct.Rows[0][2].ToString();
                job.dateStarted = dtblProduct.Rows[0][3].ToString();
                job.dateFinished = dtblProduct.Rows[0][4].ToString();
                job.status = dtblProduct.Rows[0][5].ToString();


                System.Diagnostics.Debug.WriteLine(job.jobID);
                System.Diagnostics.Debug.WriteLine(job.taskName);
                System.Diagnostics.Debug.WriteLine(job.description);
                System.Diagnostics.Debug.WriteLine(job.dateStarted);
                System.Diagnostics.Debug.WriteLine(job.dateFinished);
                System.Diagnostics.Debug.WriteLine(job.status);
                return View(job);

            }
            else
            {
                return RedirectToAction("List");
            }




        }

        [HttpPost]
        public ActionResult Edit(jobModel job)
        {
            string connectionString = @"server=localhost;user id=root;database=mvcdb";

            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                string update = "UPDATE `job info` SET `Task Name` =@taskName, Description=@description, `Date Started`=@dateStarted, `Date Finished`=@dateFinished, `Status`=@status WHERE `JobID` = @jobID";
                MySqlCommand cmd = new MySqlCommand(update, connection);
                cmd.Parameters.AddWithValue("@jobID", job.jobID);
                cmd.Parameters.AddWithValue("@taskName", job.taskName);
                cmd.Parameters.AddWithValue("@description", job.description);
                cmd.Parameters.AddWithValue("@dateStarted", job.dateStarted);
                cmd.Parameters.AddWithValue("@dateFinished", job.dateFinished);
                cmd.Parameters.AddWithValue("@status", job.status);


                cmd.ExecuteNonQuery();
                System.Diagnostics.Debug.WriteLine(job.jobID);
                System.Diagnostics.Debug.WriteLine(job.taskName);
                System.Diagnostics.Debug.WriteLine(job.description);
                System.Diagnostics.Debug.WriteLine(job.dateStarted);
                System.Diagnostics.Debug.WriteLine(job.dateFinished);
                System.Diagnostics.Debug.WriteLine(job.status);



            }
            return RedirectToAction("List");
          

        }

        public ActionResult Delete(int id)
        {
            string connectionString = @"server=localhost;user id=root;database=mvcdb";

            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();
                string delete = "DELETE FROM `job info` WHere JobID = @jobID";
                MySqlCommand cmd = new MySqlCommand(delete, connection);
                cmd.Parameters.AddWithValue("@jobID", id);
                cmd.ExecuteNonQuery();
            }

            return RedirectToAction("List");
        }



    }
}

MVCDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HOME", "Index", "job", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVCDatabase/Views/job/Edit.cshtml
@model MVCDatabase.Models.jobModel

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Job Details</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.jobID)


    <div class="form-group">
        @Html.LabelFor(model => model.taskName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.taskName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.taskName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dateStarted, htmlAttributes: new { @class = "control-label col-md-2"})
        <div class="col-md-10">
            @Html.EditorFor(model => model.dateStarted, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.dateStarted, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dateFinished, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dateFinished, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
            @Html.ValidationMessageFor(model => model.dateFinished, "", new { @class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

MVCDatabase/Views/job/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Job Details</h1>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>

@using (Html.BeginForm("Index", "job", FormMethod.Post))

{
    <table>
        <tr>
            <th>Task Name: @Html.TextBox("taskName", null)</th>
        </tr>
        <tr>
            <th>Description: @Html.TextArea("description", new { @class = "form-control", @cols = 20, @rows = 5 }) </th>
        </tr>
        <tr>
            <th>Date Started: @Html.TextBox("dateStarted", null, new { @type = "date" }) </th>
        </tr>
        <tr>
            <th>Date Finished: @Html.TextBox("dateFinished", null, new { @type = "date" }) </th>
        </tr>
        <tr>
            <th>Status: @Html.TextBox("status", null) </th>
        </tr>
        <tr></tr>
    </table>
    <input type="submit" value="Save" />
}
@using (Html.BeginForm("List", "job", FormMethod.Post))
{
    <input type="submit" value="List"/>
}

MVCDatabase/Views/job/List.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "List";
}


<center><h1>List</h1></center>
<style>
    table, th, td {
        border: 1px solid black;
    }
</style>
<table>
    <tr>
        <th>Job ID</th>
        <th>Task Name</th>
        <th>Description</th>
        <th>Date Started</th>
        <th>Date Finished</th>
        <th>Status</th>
        <th></th>
    </tr>
    @for(int i = 0; i < Model.Rows.Count; i++)
    {
    <tr>
        <td>@Model.Rows[i][0]</td>
        <td>@Model.Rows[i][1]</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][3]</td>
        <td>@Model.Rows[i][4]</td>
        <td>@Model.Rows[i][5]</td>
        <td>
            <a href="@Url.Action("Edit", "job", new { @id = Model.Rows[i][0] })">Edit</a>
            <a href="@Url.Action("Delete", "job", new { @id = Model.Rows[i][0] })">Delete</a>
        </td>
    </tr>
    }

</table>